#!/bin/bash
clear
cd Logo && ./introxt_logo
cd ..
echo "Enter Mobile Number";
read mobileNo;
echo "Enter Password";
read password;
echo "Enter The Number Which Will Receive The Message";
read num;
curl -i 'http://www.way2sms.com/re-login' -H 'Origin: http://www.way2sms.com' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.9' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'Accept: */*' -H 'Referer: http://www.way2sms.com/' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' --data 'mobileNo='$mobileNo'&password='$password'&CatType=' --compressed -o send.txt
grep -v 'HTTP/1.1 200 OK' send.txt > me.txt
grep -v 'Server: Apache-Coyote/1.1' me.txt > me1.txt
grep -v 'Content-Type: text/plain;charset=ISO-8859-1' me1.txt > me2.txt
grep -v 'Date: Wed, 25 Jul 2018 18:30:16 GMT' me2.txt > me3.txt
grep -v 'Connection: close' me3.txt > me4.txt
grep -v 'Transfer-Encoding: chunked' me4.txt > me5.txt
grep -v 'Content-Encoding: gzip' me5.txt > me6.txt
grep -v 'send-sms' me6.txt > me7.txt
sed "s/Set-Cookie://g" me7.txt > me8.txt
sed "s/JSESSIONID=//g" me8.txt > me9.txt
sed "s/HttpOnly//g" me9.txt > me10.txt
sed "s/Path=//g" me10.txt > me11.txt
sed -e 's/[;,()'\'']/ /g;s/  */ /g' me11.txt > me12.txt
declare -a arr;
arr=($(sed -e 's/[;,()'\'']/ /g;s/  */ /g' me11.txt ));
echo ${arr[0]};
echo ${arr[0]} > jason
declare token
token=($(sed 's/^....//' jason)) 
echo $token;
declare This_host
This_host=$(hostname)
echo $This_host
curl -i 'http://www.way2sms.com/send-sms' -H 'Connection: keep-alive' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8' -H 'Referer: http://www.way2sms.com/' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.9' -H 'Cookie: JSESSIONID='${arr[0]}'' --compressed -o send.txt
curl -i 'http://www.way2sms.com/smstoss' -H 'Cookie: JSESSIONID='${arr[0]}'; _ga=GA1.2.1353417026.1532541936; _gid=GA1.2.1238403453.1532541937; __gads=ID=b990a6dcdf248b49:T=1532541937:S=ALNI_Mb2gNP3QOhegV0JrkQgy0jgdz7_Jg' -H 'Origin: http://www.way2sms.com' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.9' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'Accept: */*' -H 'Referer: http://www.way2sms.com/send-sms' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' --data 'Token='$token'&message=Introxt '$This_host' is up &toMobile='$num'&ssaction=ss' --compressed -o send.txt
if [ $? -eq 0 ]
then 
echo "Message Successfully sent";
fi




